### ISSUE TITLE
PBRTv3 Scenes Are Unavailable

### ISSUE THREAD

**Issue by Xaldew** [mmp/pbr-book-website#15]
It seems like the example scenes for PBRTv3 are unavailable (https://pbrt.org/scenes-v3) due to a HTTP Strict Transport Security (HSTS) violation (currently, via the URL https://pub-49ca6a23a58a46ef9cf5a5b34413a7ba.r2.dev/pbrt-v3-scenes.tar.gz)

**Comment by mmp** [comment]
"Works for me". Can you say more about how you're trying to download it (browser, etc.)?

**Comment by Xaldew** [comment]
Ah, I'd forgotten I had opened this issue. I'll close it. It _seems_ like this is some security "feature" for our company intranet, as this only happens while trying to access these links from work. In any case, this looks like a "me" problem rather than anything else
