### ISSUE TITLE
Typo on section 2.2.2 Importance Sampling

### ISSUE THREAD

**Issue by DeJhon-Huang** [mmp/pbr-book-website#16]
Is figure 2.2 in section 2.2 wrong?

![image](https://github.com/mmp/pbr-book-website/assets/18584942/76cf882e-1425-4327-a4be-725736365b17)

It should look like this, right?

![image](https://github.com/mmp/pbr-book-website/assets/18584942/d91080fd-0a67-4ea3-95dd-29c7904183ba)

**Comment by mmp** [comment]
Nice find, thanks for reporting this! I will be pushing an updated version with that corrected in a few hours. (I will fix by updating the underlying equation rather than redoing the plots since that's easier 😎 )
