### ISSUE TITLE
3.3.3 Coordinate System From a Vector - Equation wrong

### ISSUE THREAD

**Issue by steimich96** [mmp/pbr-book-website#18]
The equation in this section is wrong and does not fit the given implementation [Link](https://www.pbr-book.org/4ed/Geometry_and_Transformations/Vectors#CoordinateSystemfromaVector).

The "1-" should be moved in front of the fraction (out of the numerator). See also this post on math stackexchange: [https://math.stackexchange.com/questions/4838905/coordinate-system-from-a-3d-unit-vector/4839260#4839260](Link)

**Comment by mmp** [comment]
Thanks for reporting this! It was actually in the [errata](https://www.pbrt.org/errata-4ed) since last May but the text wasn't fixed in the online book. The next push (in a few hours) will have it fixed.
